### ISSUE TITLE
CRAN failure

### ISSUE THREAD

**Issue by hadley** [dipterix/ravetools#10] opened 2024-11-07 13:54 UTC
Unfortunately the recent waldo release broke your package on CRAN because it no longer imports tibble, and your package was implicitly depending on it. The easiest fix is to just make the dependency explicit, by adding tibble to Suggests.

Many apologies for the hassle. Unfortunately we didn't discover this prior to CRAN release because we had a bug in the code that runs our revdep checks 🙁.

**Comment by dipterix** [comment] 2024-11-07 19:18
No problem @hadley . Thanks for telling me this in person. CRAN has asked me to fix it, which shouldn't be an issue.

However, one question that I have is does `testthat` also import `bit64` before? My another package `filearray` does not rely on `bit64` anywhere (only sets the classname) but testing package requires `bit64`: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/filearray-00check.html

**Comment by hadley** [comment] 2024-11-07 20:03
The bit64 thing was a waldo bug and should be fixed shortly.

**Comment by dipterix** [comment] 2024-11-07 21:07
Got it. Thanks! These packages are actively maintained so you guys are not causing extra work at all. Thanks for developing these amazing packages.

**Comment by dipterix** [comment] 2024-11-12 15:11
Closing this issue as the problem is resolved in a new version, which has been submitted to CRAN

**Closed by dipterix** 2024-11-12 15:11 UTC
